### ISSUE TITLE
CmdGen breaks with Python v3.9

### ISSUE THREAD

**Issue by psyhtest** [krai/ck-mlperf#5]
A typical example:
```
rpi4$ ck run cmdgen:benchmark.image-classification.tflite-loadgen \
--model=resnet50 --mode=performance --scenario=singlestream \
--library=armnn-v21.11-neon --sut=rpi4 --target_latency=300
<...>
CK error: problem converting text to json (__init__() got an unexpected keyword argument 'encoding')!

rpi4$ python3 --version
Python 3.9.7
```
This is one of the reasons we are still using Python v3.7 and v3.8 with [CK-QAIC](https://github.com/krai/ck-qaic).

See similar problems elsewhere e.g. https://github.com/Tribler/tribler/issues/5744.

**Comment by ens-lg4** [comment]
The minimal example that still works in python3.8 and fails in python3.9 seems to be:
```
ck version "@@@{'meta':{}}"
```

**Comment by ens-lg4** [comment]
It is not really a CmdGen problem - I traced it to `json.loads()` call in the CK kernel and reported to @gfursin via CK Slack.

**Comment by gfursin** [comment]
Hmm. I didn't use Python 3.9 with CK yet. Need to check.
@ens-lg4 - I didn't see your message on Slack. Did you use #ck channel in the MLCommons slack? All other Slack channels are deprecated since last summer.
Also, I suggest to open a ticket on https://github.com/mlcommons/ck/issues because I use/check it more often ...
Thanks!

**Comment by ens-lg4** [comment]
@gfursin No problem, please see https://github.com/mlcommons/ck/issues/184

**Comment by gfursin** [comment]
Cool! THank you @ens-lg4 . Let me check it ...

**Comment by psyhtest** [comment]
> Did you use #ck channel in the MLCommons slack? All other Slack channels are deprecated since last summer.

In fact, MLCommons no longer use Slack either, [having switched to using Discord](https://mlcommons.org/en/get-involved/#getting-started):

> MLCommons uses Discord for group collaboration and communication.
> The invite code for our Discord server is https://discord.gg/emD2ge5EjG and the server name is “MLCommons”.

**Comment by gfursin** [comment]
I believe this issue should be fixed in V2.6.1.

@psyhtest - I sometimes go to MLCommons at Discord but we still use Slack for most of our projects so there are more chances that I will spot new messages on Slack than on Discord ;) ...

**Comment by psyhtest** [comment]
@gfursin Same here. since MLCommons just ban using Slack, should be go back to the good old collective-knowledge.slack.com?
